spring:
  application:
    name: commerce

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  logging:
    level:
      org.hibernate.SQL: debug

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: your-secret-key
